browser=chrome
url=https://qa.instulearn.com
login_url=https://qa.instulearn.com/login
mail=ahmet.student@instuLearn.com
password=Learn.123!
register_url=https://qa.instulearn.com/register
timeout=10

tsMail=tural.seyidov.student@instulearn.com


inStudentGecerliMail=ilkin.abakarov.student@instulearn.com
inStudentGecerliPassword=Learn.123!
inTeacherGecerliMail=ilkin.abakarov.teacher@instulearn.com
inTeacherGecerliPassword=Learn.123!

inStudentGecersizMail= ilkin.abakarov.student@instulearn.con
inStudentGecersizPassword=Learn.123!!
inTeacherGecersizMail=ilkin.abakarov.teacher@instulearn.con
inTeacherGecersizPassword=Learn.123!!


#27 30 arasi Samet hoca
#31 36 arasi Burak hoca
#37 42 arasi Huseyin hoca








googleUrl=https://www.google.com/


instructorGecerliMail = huseyin.ozger.teacher@instulearn.com
studentGecerliMail = huseyin.ozger.student@instulearn.com
organizationGecerliMail = huseyin.ozger@instulearn.com
GecerliPassword = Learn.123!
GecersizMail = gecersizMail@instulearn.com
GecersizPassword = Learn.1234
