browser=chrome
url=https://qa.instulearn.com
login_url=https://qa.instulearn.com/login
mail=ahmet.student@instuLearn.com
password=Learn.123!
register_url=https://qa.instulearn.com/register
timeout=10
googleUrl=https://www.google.com/

tsMail=tural.seyidov.student@instulearn.com


